### ISSUE TITLE
Wygląd naszego projektu

### ISSUE THREAD

**Issue by ivansportfolio** [ivansportfolio/react-native-app#3]
[TUTAJ ](https://github.com/ivansportfolio/react-native-app/wiki) mamy projekt o krótki opis naszego projektu oraz mockupy @p1b1

**Comment by ivansportfolio** [comment]
I to jest propozycja. Jak miałbyś coś innego na oku śmiało dawaj znać ;)

**Comment by p1b1** [comment]
Dla mnie boma, czysto i przejrzyście :)
