### ISSUE TITLE
Jakbyśmy zaczęli prace nad projektem

### ISSUE THREAD

**Issue by ivansportfolio** [ivansportfolio/react-native-app#4]
No i teraz tak. Mam pomysł jakbyśmy zaczęli prace nad projektem. 
1. Rozpisałbym wszystko na takie Issues. 
2. Każdy z nas który miałby chwile czasu na prace nad zadaniem przypisuje je do siebie .
3. Odbijamy się z głównej galęzi i tworzymy feature branche i dajemy je do code review. 

co Ty na to na taki start pracy w naszym projekcie ?. Czy jakąś inną wizje miałbyś na to @p1b1 ?

**Comment by p1b1** [comment]
Jestem za :) Czy chcemy może jire utworzyć na ten projekt? Będzie chyba łatwiej z taskami. Czy aż tak bardzo niechcemy w to iść?

**Comment by ivansportfolio** [comment]
Jak najbardziej postaram się stworzyć tablicę i poleicmy ;-)

**Comment by ivansportfolio** [comment]
No dobra wysłałem Ci zapkę do jiry. Jak coś jest tu jeszcze link : https://marciniwanczyk2.atlassian.net/jira/software/projects/KAN/boards/1?atlOrigin=eyJpIjoiOGVjYjBhOThjMWQ3NDRjNDk2YzMzMGI4MmI0NmM4OWEiLCJwIjoiaiJ9 daj znać czy możesz dostać się

**Comment by ivansportfolio** [comment]
Tak jak najbardziej jestem za powiedz tylko @p1b1 czy masz wjazd do jiry to zrobie taski nam aby było po Bożemu

**Comment by ivansportfolio** [comment]
Bo wyslałem Ci @p1b1 linka wyżej i zaproszenie

**Comment by p1b1** [comment]
Jest i działa :)
